import copy, json, os
from pathlib import Path
import requests
from .cache import ROOT
from .modloaders import install_loader
from .launcher import launch
from .net import download

LIBS=ROOT/"libraries"
UA="mcli/0.8.5"

class LoaderLaunchError(RuntimeError): pass

def _maven_path(name):
    parts=name.split(":")
    if len(parts)<3: raise LoaderLaunchError("Bad Maven coordinate: "+name)
    group,artifact,version=parts[:3]
    classifier=parts[3] if len(parts)>3 else None
    fn=f"{artifact}-{version}" + (f"-{classifier}" if classifier else "") + ".jar"
    return "/".join(group.split("."))+f"/{artifact}/{version}/{fn}"

def _ensure_profile_libs(profile):
    cp=[]
    for lib in profile.get("libraries",[]):
        name=lib.get("name")
        if not name: continue
        downloads=lib.get("downloads",{})
        art=downloads.get("artifact")
        if art and art.get("url"):
            dest=LIBS/art["path"]
            if not dest.exists(): download(art["url"],dest,art.get("sha1"))
            cp.append(str(dest)); continue
        path=_maven_path(name)
        url=lib.get("url")
        if not url:
            # Fabric/Quilt profiles normally provide Maven repository URLs.
            url="https://libraries.minecraft.net/"
        if not url.endswith("/"): url+="/"
        dest=LIBS/path
        if not dest.exists():
            r=requests.get(url+path,stream=True,timeout=60,headers={"User-Agent":UA})
            r.raise_for_status(); dest.parent.mkdir(parents=True,exist_ok=True)
            with dest.open("wb") as f:
                for c in r.iter_content(1024*1024):
                    if c:f.write(c)
        cp.append(str(dest))
    return cp

def _merge(base,profile):
    meta=copy.deepcopy(base)
    # Loader profile overrides the entry point and contributes libraries/arguments.
    if profile.get("mainClass"): meta["mainClass"]=profile["mainClass"]
    meta["libraries"]=meta.get("libraries",[])+profile.get("libraries",[])
    pa=profile.get("arguments",{})
    if pa:
        meta.setdefault("arguments",{})
        meta["arguments"]["jvm"]=meta["arguments"].get("jvm",[])+pa.get("jvm",[])
        meta["arguments"]["game"]=meta["arguments"].get("game",[])+pa.get("game",[])
    # Some older loader profiles use minecraftArguments.
    if profile.get("minecraftArguments"):
        old=meta.get("minecraftArguments","")
        meta["minecraftArguments"]=(old+" "+profile["minecraftArguments"]).strip()
    return meta

def launch_profile(loader,version,client_jar,base_meta,game_dir=None,loader_version=None):
    if loader not in ("fabric","quilt"):
        raise LoaderLaunchError(
            f"One-command launch metadata merge is currently implemented for Fabric/Quilt; "
            f"{loader} uses installer-generated launcher metadata and needs a different import path."
        )
    profile_path,lv=install_loader(loader,version.id,loader_version)
    profile=json.loads(Path(profile_path).read_text(encoding="utf-8"))
    # launcher.launch already downloads libraries, but profile Maven libraries without
    # downloads.artifact need to exist first so its legacy fallback can find them.
    _ensure_profile_libs(profile)
    merged=_merge(base_meta,profile)
    proc=launch(version,client_jar,merged,game_dir)
    return proc,lv


def _find_installed_profile(client_dir, loader, mc, lv):
    root=Path(client_dir)
    versions=root/"versions"
    if not versions.exists():
        raise LoaderLaunchError(f"{loader} installer did not create a versions directory.")
    candidates=[]
    for js in versions.glob("*/**/*.json"):
        try:
            data=json.loads(js.read_text(encoding="utf-8"))
        except Exception:
            continue
        ident=str(data.get("id","")).lower()
        main=str(data.get("mainClass","")).lower()
        score=0
        if loader in ident: score+=5
        if str(lv).lower() in ident: score+=3
        if str(mc).lower() in ident: score+=2
        if loader=="forge" and "modlauncher" in main: score+=1
        if loader=="neoforge" and ("modlauncher" in main or "neoforge" in ident): score+=1
        if score: candidates.append((score,js,data))
    if not candidates:
        raise LoaderLaunchError(f"Could not locate the launcher profile generated by {loader}.")
    candidates.sort(key=lambda x:x[0],reverse=True)
    return candidates[0][1],candidates[0][2]

def _import_installer_libraries(client_dir):
    src=Path(client_dir)/"libraries"
    if not src.exists(): return
    import shutil
    LIBS.mkdir(parents=True,exist_ok=True)
    shutil.copytree(src,LIBS,dirs_exist_ok=True)

def launch_installer_profile(loader,version,client_jar,base_meta,game_dir=None,loader_version=None):
    if loader not in ("forge","neoforge"):
        raise LoaderLaunchError("Installer profile launch is for Forge/NeoForge.")
    client_dir,lv=install_loader(loader,version.id,loader_version)
    profile_path,profile=_find_installed_profile(client_dir,loader,version.id,lv)
    _import_installer_libraries(client_dir)

    # Forge/NeoForge generated profiles use inheritsFrom. MCLI already has the
    # corresponding vanilla metadata, so merge the generated child profile into it.
    merged=_merge(base_meta,profile)

    # Generated profiles may contain library entries whose artifacts are already
    # installed into the temporary launcher tree. Importing that tree above makes
    # launcher.py's Maven-coordinate fallback resolve them from ~/.mcli/libraries.
    proc=launch(version,client_jar,merged,game_dir)
    return proc,lv,profile_path
